In [1]:
import numpy as np
np.seterr(divide='ignore', invalid='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [2]:
m = 9019

Moje oceny:

In [3]:
my_ratings = np.zeros((m,1))
my_ratings[2571] = 5 #Matrix
my_ratings[32] = 4 #Twelve Monkeys
my_ratings[260] = 5 #Star Wars
my_ratings[1097] = 4
my_ratings = np.nan_to_num(my_ratings/np.linalg.norm(my_ratings, axis=0)) #normalizacja macierzy

Importowanie danych

In [4]:
X = [np.zeros(m)]
current_user_id=1
with open('./ml-latest-small/ratings.csv', 'r') as file:
    file.readline()
    for line in file:
        line = line.split(',')
        if int(line[1]) < m:
            if int(line[0]) == current_user_id:
                X[current_user_id-1][int(line[1])] = float(line[2])
            else:
                current_user_id += 1
                X.append(np.zeros(m))
                X[current_user_id-1][int(line[1])] = float(line[2])
X

[array([0., 4., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 4., 0., ..., 0., 0., 0.]),
 array([0., 0., 4., ..., 0., 0., 0.]),
 array([0. , 4.5, 0. , ..., 0. , 0. , 0. ]),
 array([0., 0., 4., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0. , 2.5, 0. , ..., 0. , 0. , 0. ]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0. , 4.5, 0. , ..., 0. , 0. , 0. ]),
 array([0. , 3.5, 3. , ..., 0. , 0. , 0. ]),
 array([0., 4., 3., ..., 0., 0., 0.]),
 array([0., 0., 3., ..., 0., 0., 0.]),
 array([0. , 3.5, 3.5, ..., 0. , 0. , 0. ]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0

Normalizacja macierzy X

In [5]:
X = np.array(X)
X = np.nan_to_num(X/np.linalg.norm(X, axis=0))

Obliczanie macierzy Z oraz rekomendacji

In [6]:
Z = np.dot(X,my_ratings)
Z = Z/np.linalg.norm(Z)
Res = np.dot(X.T,Z)

Lista posortowanych wyników

In [7]:
t = list(Res)
Recommendations = []
for i in range(len(t)):
    Recommendations.append((t[i][0],i))
Recommendations.sort(reverse=True)
Recommendations

[(0.8675507828468106, 260),
 (0.8362098349303672, 2571),
 (0.8227451213877746, 1196),
 (0.8002349214247858, 1210),
 (0.7458504689612445, 1097),
 (0.728602915973311, 32),
 (0.7265369898748618, 1198),
 (0.7095672455110476, 1240),
 (0.7029872178855614, 1270),
 (0.698149276879729, 1291),
 (0.6973450359077008, 2028),
 (0.6842728560727938, 589),
 (0.6787406267628276, 2762),
 (0.6779667543055926, 1580),
 (0.6728379041160385, 296),
 (0.6676556828598865, 1265),
 (0.6646471678885215, 1214),
 (0.6626900312730195, 2959),
 (0.6596566453612895, 2628),
 (0.6594203941949245, 2115),
 (0.6540016529485464, 356),
 (0.6530643237973406, 593),
 (0.6526336550930462, 1200),
 (0.6489428394420657, 2858),
 (0.6488946378391319, 1036),
 (0.6449572263952317, 858),
 (0.6445304483692085, 480),
 (0.6431397517228065, 780),
 (0.6396810746052387, 608),
 (0.6386904805917126, 2716),
 (0.6370265382377952, 3793),
 (0.6345720620085955, 47),
 (0.6337270502590108, 1527),
 (0.63342256271754, 4993),
 (0.6317754223875668, 1089),
 (

Importowanie i wyświetlanie tytułów filmów według rekomendacji

In [8]:
movies = dict()
with open('./ml-latest-small/movies.csv', 'r') as file:
    file.readline()
    for movie in file:
        movie = movie.split(',')
        if int(movie[0]) < m:
            movies.update({int(movie[0]) : movie[1]})
        else:
            break

In [9]:
for r in Recommendations:
    if movies.get(int(r[1])) is not None:
        #print(r[1],movies.get(int(r[1]))) #zostaną wypisane id + tytuł
        print(movies.get(r[1])) #sam tytuł

Star Wars: Episode IV - A New Hope (1977)
"Matrix
Star Wars: Episode V - The Empire Strikes Back (1980)
Star Wars: Episode VI - Return of the Jedi (1983)
E.T. the Extra-Terrestrial (1982)
Twelve Monkeys (a.k.a. 12 Monkeys) (1995)
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)
"Terminator
Back to the Future (1985)
Indiana Jones and the Last Crusade (1989)
Saving Private Ryan (1998)
Terminator 2: Judgment Day (1991)
"Sixth Sense
Men in Black (a.k.a. MIB) (1997)
Pulp Fiction (1994)
Groundhog Day (1993)
Alien (1979)
Fight Club (1999)
Star Wars: Episode I - The Phantom Menace (1999)
Indiana Jones and the Temple of Doom (1984)
Forrest Gump (1994)
"Silence of the Lambs
Aliens (1986)
American Beauty (1999)
Die Hard (1988)
"Godfather
Jurassic Park (1993)
Independence Day (a.k.a. ID4) (1996)
Fargo (1996)
Ghostbusters (a.k.a. Ghost Busters) (1984)
X-Men (2000)
Seven (a.k.a. Se7en) (1995)
"Fifth Element
"Lord of the Rings: The Fellowship of the Ring
Reservoir Dogs (

Night of the Comet (1984)
Date with an Angel (1987)
Mystic Pizza (1988)
Up Close and Personal (1996)
Manon of the Spring (Manon des sources) (1986)
Gossip (2000)
One Night at McCool's (2001)
Halloween III: Season of the Witch (1982)
Dog Soldiers (2002)
My First Mister (2001)
"Boy Who Could Fly
"Puppet Masters
"River
Kissing Jessica Stein (2001)
Bringing Down the House (2003)
Tremors 3: Back to Perfection (2001)
Ferngully: The Last Rainforest (1992)
"Manhattan Project
"Maltese Falcon
Celebrity (1998)
Spice World (1997)
Someone Like You (2001)
Black Knight (2001)
Backbeat (1993)
Owning Mahowny (2003)
Alice (1990)
"Tale of Two Sisters
"Dancer Upstairs
"Little Princess
Hoodlum (1997)
Tommy (1975)
Herbie Goes Bananas (1980)
Madonna: Truth or Dare (1991)
"Yards
Major League: Back to the Minors (1998)
Spriggan (Supurigan) (1998)
Dead Presidents (1995)
Jeepers Creepers 2 (2003)
Daddy Day Care (2003)
Stardust Memories (1980)
Beethoven's 2nd (1993)
Mean Streets (1973)
Pride and Prejudice (1940)


Tokyo Decadence (Topâzu) (1992)
Pinocchio (2002)
War and Peace (1956)
"Party 2
Attila (Attila Flagello di Dio) (1982)
"Do You Remember Dolly Bell? (Sjecas li se
I'm Starting From Three (Ricomincio da Tre) (1981)
First Monday in October (1981)
"Woman Next Door
"Eyewitness (Janitor
"Friend Is a Treasure
"His Secret Life (a.k.a. Ignorant Fairies
Love Me Tender (1956)
"Last Kiss
Calamity Jane (1953)
"Piano Teacher
"Town is Quiet
"Last Metro
"Party
"Cat o' Nine Tails
Sweetie (1989)
"Return of the Musketeers
Last Exit to Brooklyn (1989)
Big Deal on Madonna Street (I Soliti Ignoti) (1958)
How to Marry a Millionaire (1953)
"Faraway
"Two Women (Ciociara
"King in New York
Raining Stones (1993)
Not One Less (Yi ge dou bu neng shao) (1999)
Rosetta (1999)
And the Ship Sails On (E la nave va) (1983)
"Apple
My Name Is Joe (1998)
Steam: The Turkish Bath (Hamam) (1997)
Jamaica Inn (1939)
"Best Man
"Real Blonde
Love and Other Catastrophes (1996)
"Children Are Watching Us
"Eighth Day
Little Lord Fauntler